// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthOps struct {
	Login    interface{} `json:"login"`
	Register interface{} `json:"register"`
}

type DataMap struct {
	Count      int    `json:"count"`
	Additional *int   `json:"additional"`
	Name       string `json:"name"`
}
